== 常用指令
安裝完成後，可以使用 `ng` 命令來建立、建置、測試和啟動 Angular 應用程式。

[cols="1,3", options="header"]
|===
| 命令 | 描述

| https://angular.dev/cli/build[`ng build`^]
| **編譯 Angular 專案為生產環境版本**

| https://angular.dev/cli/serve[`ng serve`^]
| **建構應用程式並啟動開發伺服器**

| https://angular.dev/cli/generate#component-command[`ng generate`^]
| **基於後置的sub-command生成相對應的檔案**

| https://angular.dev/cli/test[`ng test`^]
| **執行單元測試**

| https://angular.dev/cli/e2e[`ng e2e`^]
| **執行端到端測試**
|===

== 補充: generate 指令
`ng generate` 指令可以用來生成 Angular 應用程式中的各種檔案，例如元件、服務、模組等。以下是一些常用的子指令：

[cols="1,3", options="header"]
|===
| 子指令 | 描述

| https://angular.dev/cli/generate/app-shell[`app-shell`^]
| **生成應用程式的App Shell**

| https://angular.dev/cli/generate/application[`application`^]
| **生成應用程式**

| https://angular.dev/cli/generate/class[`class`^]
| **生成類別**

| https://angular.dev/cli/generate#service-command[`component`^]
| **生成元件**

| https://angular.dev/cli/generate/config[`config`^]
| **生成Config檔**

| https://angular.dev/cli/generate/directive[`directive`^]
| **生成指令**

| https://angular.dev/cli/generate/enum[`enum`^]
| **生成列舉**

| https://angular.dev/cli/generate/environments[`environments`^]
| **生成環境檔案**

| https://angular.dev/cli/generate/guard[`guard`^]
| **生成一個路由守衛**

| https://angular.dev/cli/generate/interceptor[`interceptor`^]
| **生成攔截器**

| https://angular.dev/cli/generate/interface[`interface`^]
| **生成介面**

| https://angular.dev/cli/generate/library[`library`^]
| **生成函式庫**

| https://angular.dev/cli/generate/module[`module`^]
| **生成模組**

| https://angular.dev/cli/generate/pipes[`pipe`^]
| **生成管道**

| https://angular.dev/cli/generate/resolver[`resolver`^]
| **生成路由解析器**

| https://angular.dev/cli/generate/service[`service`^]
| **生成服務**

| https://angular.dev/cli/generate/service-worker[`service-worker`^]
| **生成Service Worker**

| https://angular.dev/cli/generate/web-worker[`web-worker`^]
| **生成Web Worker**

|===

=== `ng generate app-shell`

會用來產生 app shell 元件，此元件主要用來在應用程式初始載入時快速啟動靜態渲染頁面，實現出在實際內容載入前先顯示出應用程式基本骨架給使用者看

- 生成檔案結構
----
src
├── app
│   ├── app.config.server.ts
│   └── app-shell
│       ├── app-shell.component.html
│       ├── app-shell.component.css
│       ├── app-shell.component.spec.ts
│       └── app-shell.component.ts
└── main.server.ts
----

[cols="1,3", options="header"]
|===
| 檔案 | 描述

| app.config.server.ts
| **應用程式中的伺服器端配置檔案，主要用於設定 Server-Side Rendering 相關的配置**

| app-shell.component.html
| **app-shell要渲染的內容**

| app-shell.component.css
| **app-shell渲染內容的樣式**

| app-shell.component.spec
| **app-shell的單元測試**

| app-shell.component.ts
| **App Shell 功能的核心元件**

| main.server.ts
| **應用程式伺服器端的進入點**

|===

=== `ng generate application [name]`
會在專案的projects資料夾下產生新的應用程式，當專案需要多應用程式時才會使用到，例如店商網站會有不同品牌的商品，但都使用相同的應用程式邏輯

- 生成檔案
----
projects/
└── application/
    ├── public/
    ├── src/
    |   └── ...
    ├── tsconfig.app.json
    └── tsconfig.spec.json
----
除了一些共用的依賴與angular配置以外基本上檔案都跟初始應用程式是一樣的

=== `ng generate class [name]`
分別產生class檔案與class的單元測試檔案

- 生成檔案
----
app/
├── ...
├── class.ts
└── class.spec.ts
----

=== `ng generate component [name]`

產生一般的Angular元件

=== `ng generate config`

產生一些配置檔案

. karma.config.js: 用來設定單元測試環境
. .browserslistrc: 與瀏覽器相關的相容性配置

=== `ng generate directive [name]` 

用來生成自訂的屬性指令，此指令是用來改變DOM元素行為或是外觀

`生成檔案`
----
app/
├── ...
├── testDir.directive.ts
└── testDir.directive.spec.ts  // 單元測試用
----

`testDir.directive.ts`

[source,typescript]
----
import {Directive, ElementRef} from '@angular/core';
@Directive({
  standalone: true,
  selector: '[appHighlight]',
})
export class HighlightDirective {
  constructor(private el: ElementRef) {
    this.el.nativeElement.style.backgroundColor = 'yellow';
  }
}
----

- 透過@Directive裝飾器將此元件變為屬性指令
- 設定selector屬性作為屬性名稱



`app.component.html`

[source,html]
----
<p appHighlight>Highlight me!</p>
----

- 當html使用了屬性指令，便會執行元件的constructor，上述文字會變換成黃色

=== `ng generate enum [name]`
會產生通用的列舉

`生成檔案`
----
app/
├── ...
└── testEnum.ts
----

=== `ng generate environments`

會產生 Angular 環境的配置文件，用來管理不同環境下的環境變數

`生成檔案`
----
src/
├── ...
└── environments/
    ├── environment.development.ts
    └── environment.ts // 默認環境，通常為production
----

==== 簡單範例

`environment.ts`
[source,typescript]
----
export const environment = {
    env: "pro"
};
----

`environment.development.ts`
[source,typescript]
----
export const environment = {
    env: "dev"
};
----

分別在不同環境下設定相同的環境變數名，變數值表示當前的環境

`app.component.ts`
[source,typescript]
----
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { environment } from '../environments/environment'; // 匯入環境變數配置

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'appcli';
  env = environment.env; // 取得當前的環境內容
}
----

`app.component.html`
[source,html]
----
<h1>{{ env }}</h1>
----

當伺服器使用 production 配置啟動，標題會顯示pro，若使用 development 配置啟動，標題則會是dev

==== 自訂環境

也可以自訂 Angular 的執行環境

. 新增自訂環境配置:
+ 
在 `angular.json` 下的 `/architect/build/configurations` 新增 `testenv`
+
[source,json]
----
"testenv": {}
----

. 在 `environments/` 下新增自訂環境配置檔 `environment.testenv.ts`
+
`environment.testenv.ts`
+
[source,typescript]
----
export const environment = {
    env: "testenv"
}
----

. 在 `angular.json` 的 `testenv` 配置下新增 fileReplacements，用來替換 environment 檔案
+
[source,json]
----
"testenv":{
    "fileReplacements": [
        {
            "replace": "src/environments/environment.ts",
            "with": "src/environments/environment.testenv.ts"
        }
    ]
}
----

- replace: 設定要替換的environment，通常預設為environment.ts，所以都會是替換此檔案
- with: 設定要替換成哪個environment，換成剛新增的 `environment.testenv.ts` 即可

. 使用自訂的環境配置啟動伺服器
+
----
ng serve --configuration=testenv
----
+
此時 `<h1>` 標籤的內容就會變成 testenv

link:index.html[回首頁]